lib: [
  "_build/install/default/lib/categories/META"
  "_build/install/default/lib/categories/dune-package"
  "_build/install/default/lib/categories/opam"
]
lib_root: [
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Algebra.glob" {"coq/user-contrib/Categories/Algebra/Algebra.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Algebra.v" {"coq/user-contrib/Categories/Algebra/Algebra.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Algebra.vo" {"coq/user-contrib/Categories/Algebra/Algebra.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Bisimulation.glob" {"coq/user-contrib/Categories/Algebra/Bisimulation.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Bisimulation.v" {"coq/user-contrib/Categories/Algebra/Bisimulation.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Bisimulation.vo" {"coq/user-contrib/Categories/Algebra/Bisimulation.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/CategoryAlgebra.glob" {"coq/user-contrib/Categories/Algebra/CategoryAlgebra.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/CategoryAlgebra.v" {"coq/user-contrib/Categories/Algebra/CategoryAlgebra.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/CategoryAlgebra.vo" {"coq/user-contrib/Categories/Algebra/CategoryAlgebra.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/CategoryCoAlgebra.glob" {"coq/user-contrib/Categories/Algebra/CategoryCoAlgebra.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/CategoryCoAlgebra.v" {"coq/user-contrib/Categories/Algebra/CategoryCoAlgebra.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/CategoryCoAlgebra.vo" {"coq/user-contrib/Categories/Algebra/CategoryCoAlgebra.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Coalgebra.glob" {"coq/user-contrib/Categories/Algebra/Coalgebra.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Coalgebra.v" {"coq/user-contrib/Categories/Algebra/Coalgebra.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Algebra/Coalgebra.vo" {"coq/user-contrib/Categories/Algebra/Coalgebra.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Adjunction.glob" {"coq/user-contrib/Categories/Category/Adjunction.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Adjunction.v" {"coq/user-contrib/Categories/Category/Adjunction.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Adjunction.vo" {"coq/user-contrib/Categories/Category/Adjunction.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Category.glob" {"coq/user-contrib/Categories/Category/Category.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Category.v" {"coq/user-contrib/Categories/Category/Category.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Category.vo" {"coq/user-contrib/Categories/Category/Category.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/CategoryCat.glob" {"coq/user-contrib/Categories/Category/CategoryCat.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/CategoryCat.v" {"coq/user-contrib/Categories/Category/CategoryCat.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/CategoryCat.vo" {"coq/user-contrib/Categories/Category/CategoryCat.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Functor.glob" {"coq/user-contrib/Categories/Category/Functor.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Functor.v" {"coq/user-contrib/Categories/Category/Functor.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Functor.vo" {"coq/user-contrib/Categories/Category/Functor.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Transformation.glob" {"coq/user-contrib/Categories/Category/Transformation.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Transformation.v" {"coq/user-contrib/Categories/Category/Transformation.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Category/Transformation.vo" {"coq/user-contrib/Categories/Category/Transformation.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/Arrow.glob" {"coq/user-contrib/Categories/Embedding/Arrow.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/Arrow.v" {"coq/user-contrib/Categories/Embedding/Arrow.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/Arrow.vo" {"coq/user-contrib/Categories/Embedding/Arrow.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/CategoryType.glob" {"coq/user-contrib/Categories/Embedding/CategoryType.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/CategoryType.v" {"coq/user-contrib/Categories/Embedding/CategoryType.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/CategoryType.vo" {"coq/user-contrib/Categories/Embedding/CategoryType.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/FunctorsType.glob" {"coq/user-contrib/Categories/Embedding/FunctorsType.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/FunctorsType.v" {"coq/user-contrib/Categories/Embedding/FunctorsType.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/FunctorsType.vo" {"coq/user-contrib/Categories/Embedding/FunctorsType.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/Monad.glob" {"coq/user-contrib/Categories/Embedding/Monad.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/Monad.v" {"coq/user-contrib/Categories/Embedding/Monad.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Embedding/Monad.vo" {"coq/user-contrib/Categories/Embedding/Monad.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/CoAlgebraStream.glob" {"coq/user-contrib/Categories/Examples/CoAlgebraStream.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/CoAlgebraStream.v" {"coq/user-contrib/Categories/Examples/CoAlgebraStream.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/CoAlgebraStream.vo" {"coq/user-contrib/Categories/Examples/CoAlgebraStream.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Prelim.glob" {"coq/user-contrib/Categories/Examples/FRP/Prelim.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Prelim.v" {"coq/user-contrib/Categories/Examples/FRP/Prelim.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Prelim.vo" {"coq/user-contrib/Categories/Examples/FRP/Prelim.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Util.glob" {"coq/user-contrib/Categories/Examples/FRP/Util.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Util.v" {"coq/user-contrib/Categories/Examples/FRP/Util.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Util.vo" {"coq/user-contrib/Categories/Examples/FRP/Util.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Yampa.glob" {"coq/user-contrib/Categories/Examples/FRP/Yampa.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Yampa.v" {"coq/user-contrib/Categories/Examples/FRP/Yampa.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Yampa.vo" {"coq/user-contrib/Categories/Examples/FRP/Yampa.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Yampa2.glob" {"coq/user-contrib/Categories/Examples/FRP/Yampa2.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Yampa2.v" {"coq/user-contrib/Categories/Examples/FRP/Yampa2.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/FRP/Yampa2.vo" {"coq/user-contrib/Categories/Examples/FRP/Yampa2.vo"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/Stream.glob" {"coq/user-contrib/Categories/Examples/Stream.glob"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/Stream.v" {"coq/user-contrib/Categories/Examples/Stream.v"}
  "_build/install/default/lib/coq/user-contrib/Categories/Examples/Stream.vo" {"coq/user-contrib/Categories/Examples/Stream.vo"}
]
doc: [
  "_build/install/default/doc/categories/CHANGES.md"
  "_build/install/default/doc/categories/LICENSE"
  "_build/install/default/doc/categories/README.md"
]
